# Generated by Django 3.2 on 2022-05-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220523_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='previous_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='previous_question',
            field=models.IntegerField(default=0),
        ),
    ]
