# Generated by Django 3.2 on 2022-05-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220524_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='first_question',
            field=models.BooleanField(default=False),
        ),
    ]
